os:
  - linux
  # - osx
  # Note: osx seems to exhibit some of the strange lockups that I saw in github's actions.
  # Namely, that UDP packets fail to send, causing test timeouts. Research more later.
dist: xenial
before_install:
  - pwd
  - ./.ci/deno_install.sh
  - export DENO_INSTALL="$HOME/.deno"
  - export PATH="$DENO_INSTALL/bin:$PATH"
script: 
  - deno test -A --unstable
